### ISSUE TITLE
Decode unknown object constellations with known types

### ISSUE THREAD

**Issue by Onefox** [cybercongress/js-amino#46]
As you mind guess my over all goal is to process every tx on a blockchain.
This also means that I don't know the constellation of what messages are in a tx and in which order they are in.

Here is an example to show case the problem:
```js
const {
    Codec,
    FieldOtions,
    TypeFactory,
    Utils,
    Types,
    WireTypes,
} = require('js-amino');


let StdTx = TypeFactory.create('StdTx', [{
    name: 'msg',
    type: Types.ArrayInterface,
},
    {
        name: 'fee',
        type: Types.Struct,
    },
    {
        name: 'signatures',
        type: Types.ArrayStruct,
    },
    {
        name: 'memo',
        type: Types.String,
    },
]);

let MsgSend = TypeFactory.create('MsgSend', [{
    name: "to_address",
    type: Types.String,
},
    {
        name: "from_address",
        type: Types.String,
    },

    {
        name: "amount",
        type: Types.ArrayStruct
    }
]);
let MsgMultiSend = TypeFactory.create('MsgMultiSend', [{
    name: "inputs",
    type: Types.ArrayStruct
},
    {
        name: "outputs",
        type: Types.ArrayStruct
    }
]);
let Coin = TypeFactory.create('coin', [{
    name: 'denom',
    type: Types.String,
},
    {
        name: 'amount',
        type: Types.String,
    }
]);

let Input = TypeFactory.create('input', [{
    name: 'address',
    type: Types.String,
},
    {
        name: 'coins',
        type: Types.ArrayStruct,
    }
]);

let Output = TypeFactory.create('output', [{
    name: 'address',
    type: Types.String,
},
    {
        name: 'coins',
        type: Types.ArrayStruct,
    }
]);

let Fee = TypeFactory.create('fee', [{
    name: 'amount',
    type: Types.ArrayStruct,
},
    {
        name: 'gas',
        type: Types.Int64,
    }
]);


let Amount = TypeFactory.create('amount', [{
    name: 'denom',
    type: Types.String,
},
    {
        name: 'amount',
        type: Types.String,
    }
]);

let PubKeySecp256k1 = TypeFactory.create('PubKeySecp256k1', [{
    name: 's',
    type: Types.ByteSlice,
}], Types.ByteSlice)

let Signature = TypeFactory.create('signature', [{
    name: 'pub_key',
    type: Types.Interface,
},
    {
        name: 'signature',
        type: Types.ByteSlice,
    }
])

let codec = new Codec();

codec.registerConcrete(new StdTx(), 'auth/StdTx', {});
codec.registerConcrete(new MsgSend(), 'cosmos-sdk/MsgSend', {});
//codec.registerConcrete(new MsgMultiSend(), 'cosmos-sdk/MsgMultiSend', {});
codec.registerConcrete(new PubKeySecp256k1(), 'tendermint/PubKeySecp256k1', {});

let amount = new Amount('stake', "301");

let addressFrom = [ 59,58,243,13,132,163,164,202,233,7,236,93,136,166,181,175,236,69,48,186 ]
let addressTo = [ 94,222,114,42,196,107,51,203,139,142,219,243,137,60,54,250,139,153,46,168 ]

let sendMsg = new MsgSend(addressTo, addressFrom, [amount]);

let fee = new Fee([new Amount('stake', '300')], 40000);

let pubKey = new PubKeySecp256k1([2,27,24,0,255,96,147,21,64,29,132,192,108,219,59,134,206,201,126,224,63,160,24,236,170,124,164,95,43,180,6,246,250]);
let signature = [165,76,109,61,53,129,190,147,52,224,34,106,235,208,224,36,190,25,204,36,226,129,97,109,35,130,217,228,144,106,10,134,14,183,95,252,219,235,22,92,37,53,3,89,111,173,12,158,146,71,82,113,236,241,170,121,217,20,236,23,131,35,80,29];

let sig = new Signature(pubKey, signature);
let stdTx = new StdTx([sendMsg, sendMsg], fee, [sig], '');

//let jsonTx = codec.marshalJson(stdTx);
let decodedDataTx = new StdTx();

// a tx from on chain
const base64OnChain = 'hALwYl3uCj6oo2GaChRe3nIqxGszy4uO2/OJPDb6i5kuqBIUOzrzDYSjpMrpB+xdiKa1r+xFMLoaDAoFc3Rha2USAzMwMQo+qKNhmgoUXt5yKsRrM8uLjtvziTw2+ouZLqgSFDs68w2Eo6TK6QfsXYimta/sRTC6GgwKBXN0YWtlEgMzMDESEgoMCgVzdGFrZRIDMzAwEMC4AhpqCibrWumHIQIbGAD/YJMVQB2EwGzbO4bOyX7gP6AY7Kp8pF8rtAb2+hJApUxtPTWBvpM04CJq69DgJL4ZzCTigWFtI4LZ5JBqCoYOt1/82+sWXCU1A1lvrQyekkdScezxqnnZFOwXgyNQHQ==';
const hexOnChainTx = Buffer.from(base64OnChain, 'base64').toString('hex');
console.log("hex:\n", hexOnChainTx);

codec.unMarshalBinary(Utils.fromHex(hexOnChainTx), decodedDataTx);
console.log("Decoded data:\n", JSON.stringify(decodedDataTx.JsObject()));

```

In this example I am able do decode the following message so all good:
```json
{
	"msg": [{
		"to_address": "^�r*�k3ˋ���<6���.�",
		"from_address": ";:�\r�����\u0007�]�����E0�",
		"amount": [{
			"denom": "stake",
			"amount": "301"
		}]
	}, {
		"to_address": "^�r*�k3ˋ���<6���.�",
		"from_address": ";:�\r�����\u0007�]�����E0�",
		"amount": [{
			"denom": "stake",
			"amount": "301"
		}]
	}],
	"fee": {
		"amount": [{
			"denom": "stake",
			"amount": "300"
		}],
		"gas": 40000
	},
	"signatures": [{
		"pub_key": [2, 27, 24, 0, 255, 96, 147, 21, 64, 29, 132, 192, 108, 219, 59, 134, 206, 201, 126, 224, 63, 160, 24, 236, 170, 124, 164, 95, 43, 180, 6, 246, 250],
		"signature": [165, 76, 109, 61, 53, 129, 190, 147, 52, 224, 34, 106, 235, 208, 224, 36, 190, 25, 204, 36, 226, 129, 97, 109, 35, 130, 217, 228, 144, 106, 10, 134, 14, 183, 95, 252, 219, 235, 22, 92, 37, 53, 3, 89, 111, 173, 12, 158, 146, 71, 82, 113, 236, 241, 170, 121, 217, 20, 236, 23, 131, 35, 80, 29]
	}],
	"memo": []
}
```

But the problem is that I have to init the StdTx with the following line:
`let stdTx = new StdTx([sendMsg, sendMsg], fee, [sig], '');` otherwise the decoding will fail with:
```js
js-amino-example/node_modules/js-amino/src/binaryDecoder.js:178
    for (let i = 0; i < instance.length; ++i) {
                                 ^

TypeError: Cannot read property 'length' of undefined
    at decodeBinaryArray (js-amino-example/node_modules/js-amino/src/binaryDecoder.js:178:34)
    at decodeBinaryField (js-amino-example/node_modules/js-amino/src/binaryDecoder.js:97:23)
    at Reflection.ownKeys.forEach (js-amino-example/node_modules/js-amino/src/binaryDecoder.js:151:13)
    at Array.forEach (<anonymous>)
    at decodeBinaryStruct (js-amino-example/node_modules/js-amino/src/binaryDecoder.js:145:34)
    at Object.decodeBinary (js-amino-example/node_modules/js-amino/src/binaryDecoder.js:40:31)
    at Codec.unMarshalBinary (js-amino-example/node_modules/js-amino/src/codec.js:136:23)
    at Object.<anonymous> (js-amino-example/index.js:149:7)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
```

As you can see I have to put in the same sendMsg twice to get it to work.

*Ideally it would be very nice to not need the line at all since you cant really predict all the array constellations because its in Interface.*

It should be able to identify witch object to use since there are prefixes on the encoded bytes.

This will also be a problem with tx that have other types of messages like the MsgMultiSend type.

*Aditional it would be also great if the encoder would add the type of the message to the decoded object* like this.:
```js
{
      "type": "cosmos-sdk/MsgSend",
      "value": {
        "from_address": "cosmos1tm08y2kydveuhzuwm0ecj0pkl29ejt4gghxw35",
        "to_address": "cosmos18va0xrvy5wjv46g8a3wc3f444lky2v96luase3",
        "amount": [
          {
            "denom": "stake",
            "amount": "301"
          }
        ]
      }
    }
```

**Comment by TanNgocDo** [comment]
Thanks for your reporting, I will answer all your questions soon

**Comment by TanNgocDo** [comment]
This library is encountering one problem with JS language.
For exp: If you define a structure like this : 
`let A = TypeFactory.create('A', [{
    name: 'b',
    type: Types.Struct,
}
]);`

`b ` is `Types.Struct` and it can be any type of Object struct, if you init :

 ` let aObj = new A(newB())`  the codec will know the default value of `b` inside  `A`, this initiation is something like caching the default value for obj. In Go, it's very easy because you can declare the true type for the first time. But anyway, do you have any suggestion for improving this ? Any idea is welcome

**Comment by TanNgocDo** [comment]
`It should be able to identify witch object to use since there are prefixes on the encoded bytes.` 
Nice idea, I think I can recursively to parse the prefix bytes for predicting the type to decode. It should be a new developbranch

**Comment by Onefox** [comment]
Here is a way cosmos/tendermit is doing it currently:
https://github.com/tendermint/go-amino#prefix-bytes-to-identify-the-concrete-type

If thats to much just giving in a list would also be great like here:
https://github.com/binance-chain/javascript-sdk/blob/cd52817f8eae7eb81d32639fc0a9a68ea01dc2c5/src/tx/index.js#L23
Just putting it in as an additional param in the registerConcrete function would be a easy solution or?

**Comment by TanNgocDo** [comment]
Yes, that's actually the Js-Amino is doing. I parse whole byte array to read the prefixes and know which type to decode. But As I told you before, you know a "123" prefix number is belong to which registered type but you can not know exactly the Types.Struct inside it(if you don't init it for the first time). With Go, the compiler takes care for you, but with JS, it's very tricky

**Comment by Onefox** [comment]
I think I am lacking the JS knowledge here, naively could a very ugly way be try and error?
So just building up each possible object and then trying if it fits?

**Comment by TanNgocDo** [comment]
Yes, when you Init one object, the "codec" will know the "concrete type" to decode it later. I'm very sorry if it's a work-around until now

**Comment by TanNgocDo** [comment]
anyway, the plan for this improvement will be started soon
